import type { Metadata } from 'next';

import { C, Callout, Code, DocHeader, H2, H3, P, Related } from '@/components/docs/prose';

export const metadata: Metadata = {
  title: 'Firewall contract: Qeltrun docs',
  description: 'The QeltrunPayoutFirewallV2 functions, events, and errors.',
  alternates: { canonical: '/docs/contracts' },
};

export default function Page() {
  return (
    <article>
      <DocHeader
        kind="Reference"
        title="Firewall contract"
        intro="The public surface of QeltrunPayoutFirewallV2: the functions that move a request through its lifecycle, plus the events and errors it emits."
      />

      <Callout tone="note" title="Generated ABI">
        The exact ABI is generated by <C>pnpm run export:abi:v2</C> and lives at{' '}
        <C>src/contracts/generated/firewall-v2-abi.ts</C>. This page names the surface; the ABI is
        the source of truth for encoding.
      </Callout>

      <H2 id="lifecycle">Lifecycle functions</H2>

      <H3>registerVendor</H3>
      <Code>registerVendor(vendorId, payoutWallet, approver, treasuryReviewer, riskReviewer)</Code>
      <P>
        Registers a vendor with its current payout wallet and its three reviewer seats. The four
        addresses must be distinct and non-zero. Owner only.
      </P>

      <H3>openChangeRequest</H3>
      <Code>openChangeRequest(vendorId, proposedWallet, nonce) returns (requestId)</Code>
      <P>
        Opens a request to move the vendor's payout wallet to <C>proposedWallet</C>. Reverts if the
        proposed wallet equals the current wallet. The request id is derived on chain.
      </P>

      <H3>submitPrivateSignal</H3>
      <Code>submitPrivateSignal(requestId, encryptedSignal, handleProof)</Code>
      <P>
        Submits one reviewer's sealed position. Only the three reviewer seats may call it, and each
        may call it once. After the third position the contract seals the aggregate verdict.
      </P>

      <H3>settleApproval</H3>
      <Code>settleApproval(requestId, decryptionProof)</Code>
      <P>
        Settles the request with the gateway's decryption proof for the verdict. Permissionless. If
        the verdict is yes, the payout wallet moves. If it is no, it does not.
      </P>

      <H2 id="governance">Governance functions</H2>
      <P>Approver rotation and recovery, with a seven-day, vetoable recovery delay.</P>
      <Code>{`proposeApproverRotation(vendorId, newApprover)
acceptApproverRotation(vendorId)
cancelApproverRotation(vendorId)
acceptApproverRecovery(vendorId)
cancelApproverRecovery(vendorId)
pause()
unpause()`}</Code>

      <H2 id="views">View functions</H2>
      <Code>{`isPayoutAllowed(vendorId, destination) returns (bool, string)
deriveRequestId(...) returns (bytes32)
getVendor(vendorId) returns (Vendor)
getRequest(requestId) returns (ChangeRequest)`}</Code>
      <P>
        <C>isPayoutAllowed</C> returns the gate decision and a reason code. These reads need no
        wallet, so the console renders live state before anyone connects.
      </P>

      <H2 id="events">Events</H2>
      <Code>{`VendorRegistered(...)
ChangeRequestOpened(vendorId, requestId, ...)
PrivateSignalSubmitted(requestId, reviewer, handle)
AggregateVerdictSealed(requestId, verdictHandle)
ApprovalSettled(requestId, approved)
PayoutWalletChanged(vendorId, previousWallet, newWallet)
ApproverChanged(vendorId, previousApprover, newApprover, approverEpoch)
ApproverRecoveryScheduled(vendorId, newApprover, executeAfter)`}</Code>
      <P>
        <C>ChangeRequestOpened</C> and <C>PrivateSignalSubmitted</C> are the source the console
        reads to find the shared request id and its sealed handles.
      </P>

      <H2 id="errors">Errors</H2>
      <P>The contract reverts with typed errors. The common ones during a flow:</P>
      <Code>{`DestinationUnchanged(vendorId, proposedWallet)
RequestNotCollecting(requestId, status)
RequestNotSealed(requestId, status)
UnauthorizedReviewer(vendorId, caller)
SignalAlreadySubmitted(requestId, reviewer)
StaleApproverEpoch(requestId, expectedEpoch, actualEpoch)
RecoveryNotReady(vendorId, executeAfter)`}</Code>

      <Related
        links={[
          { label: 'Run the three-reviewer flow', href: '/docs/reviewer-flow' },
          { label: 'Confidential approval', href: '/docs/confidential-model' },
          { label: 'Proof', href: '/proof' },
        ]}
      />
    </article>
  );
}
