/**
 * Copy the compiled firewall ABI into the web app.
 *
 * The frontend needs the ABI at build time, and hand-copying it is how a UI ends up calling a
 * function signature the contract no longer has. `pnpm run export:abi` regenerates it from the
 * Hardhat artifact, and `pnpm run verify` runs it so a stale copy shows up as a dirty git tree.
 */
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const ARTIFACT = join(
  process.cwd(),
  'artifacts/contracts/QeltrunPayoutFirewall.sol/QeltrunPayoutFirewall.json',
);
const TARGET = join(process.cwd(), 'web/lib/firewall-abi.ts');

const artifact = JSON.parse(await readFile(ARTIFACT, 'utf8')) as { abi: unknown[] };

const contents = `// Generated by \`pnpm run export:abi\`. Do not edit by hand.
export const FIREWALL_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

await mkdir(dirname(TARGET), { recursive: true });
await writeFile(TARGET, contents, 'utf8');

console.log(`Wrote ${artifact.abi.length} ABI entries to web/lib/firewall-abi.ts`);
