import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

const exports = [
  {
    artifact: 'artifacts/contracts/QeltrunPayoutFirewallV2.sol/QeltrunPayoutFirewallV2.json',
    target: 'src/contracts/generated/firewall-v2-abi.ts',
    name: 'FIREWALL_V2_ABI',
  },
  {
    artifact:
      'artifacts/contracts/integrations/QeltrunSafePayoutModule.sol/QeltrunSafePayoutModule.json',
    target: 'src/contracts/generated/safe-payout-module-abi.ts',
    name: 'SAFE_PAYOUT_MODULE_ABI',
  },
] as const;

for (const item of exports) {
  const parsed = JSON.parse(await readFile(join(process.cwd(), item.artifact), 'utf8')) as {
    abi: unknown[];
  };
  const target = join(process.cwd(), item.target);
  await mkdir(dirname(target), { recursive: true });
  await writeFile(
    target,
    `// Generated by \`pnpm run export:abi:v2\`. Do not edit by hand.\nexport const ${item.name} = ${JSON.stringify(parsed.abi, null, 2)} as const;\n`,
    'utf8',
  );
  console.log(`Wrote ${parsed.abi.length} ABI entries to ${item.target}`);
}
