import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { NextConfig } from 'next';

const here = dirname(fileURLToPath(import.meta.url));

const config: NextConfig = {
  reactStrictMode: true,
  // The gate logic and request-id derivation live in `../src/domain` and are shared with the
  // contract tests. Compiling them here rather than copying them is what keeps the UI from
  // drifting away from the thing it is a client for.
  transpilePackages: [],
  webpack(cfg) {
    // `../src` is written as NodeNext ESM, so its relative imports carry `.js` extensions that
    // point at `.ts` files on disk.
    cfg.resolve.extensionAlias = { ...cfg.resolve.extensionAlias, '.js': ['.ts', '.js'] };
    cfg.resolve.alias = {
      ...cfg.resolve.alias,
      '@qeltrun/domain': join(here, '../src/domain/index.ts'),
      '@qeltrun/local-gateway': join(here, '../src/providers/local-gateway-approval-provider.ts'),
      // Dependency-free, so the browser gets the same gateway wait as the scripts without
      // pulling `@iexec-nox/handle` (and therefore `ethers`) at module load.
      '@qeltrun/nox-decrypt': join(here, '../src/providers/decrypt-when-indexed.ts'),
      // Generated by `pnpm run export:abi:v2`, which runs inside `pnpm run verify`, so a stale
      // ABI shows up as a dirty git tree instead of a silent mismatch at runtime.
      '@qeltrun/abi': join(here, '../src/contracts/generated/firewall-v2-abi.ts'),
    };
    // Optional node built-ins reached for by wallet connectors, never executed in the browser.
    cfg.resolve.fallback = { ...cfg.resolve.fallback, fs: false, net: false, tls: false };
    return cfg;
  },
};

export default config;
